/* eslint-disable no-template-curly-in-string */
/* eslint-disable global-require */
// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const Services = {};
// eslint-disable-next-line no-use-before-define
loadServices();

//  _   _  _         _      _                     _          _
// | \ | |(_)       | |    | |                   | |        | |
// |  \| | _   __ _ | |__  | |_ __      __  __ _ | |_   ___ | |__
// | . ` || | / _` || '_ \ | __|\ \ /\ / / / _` || __| / __|| '_ \
// | |\  || || (_| || | | || |_  \ V  V / | (_| || |_ | (__ | | | |
// \_| \_/|_| \__, ||_| |_| \__|  \_/\_/   \__,_| \__| \___||_| |_|
//             __/ |
//            |___/

module.exports = {
  // An array of folders (excluding subfolders) where your tests are located;
  // if this is not specified, the test source must be passed as the second argument to the test runner.
  src_folders: ['tests'],

  plugins: ['./test_plugin.js'],

  webdriver: {},

  test_settings: {
    default: {
      disable_error_log: false,
      launch_url: 'http://localhost',

      screenshots: {
        enabled: false,
        path: 'screens',
        on_failure: true,
      },

      desiredCapabilities: {
        browserName: 'chrome',
      },

      webdriver: {
        start_process: true,
        server_path: '',
      },
    },
    headless: {
      desiredCapabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
          w3c: true,
          args: [
            'no-sandbox',
            'ignore-certificate-errors',
            'allow-insecure-localhost',
            'headless',
            'window-size=1920x1080',
          ],
        },
      },

      webdriver: {
        start_process: true,
        server_path: '',
        cli_args: [
          // --verbose
        ],
      },
    },
    saucelabs: {
      use_ssl: true,
      selenium: {
        start_process: false,
        host: 'ondemand.us-west-1.saucelabs.com',
        port: 443,
      },

      webdriver: {
        keep_alive: true,
        start_process: false,
      },

      desiredCapabilities: {
        browserName: 'chrome',
        platformName: 'Windows 11',
        browserVersion: 'latest',
        javascriptEnabled: true,
        acceptSslCerts: true,
        timeZone: 'New York',
        chromeOptions: {
          w3c: true,
        },
        'sauce:options': {
          username: '${SAUCE_USERNAME}',
          accessKey: '${SAUCE_ACCESS_KEY}',
          region: 'us-west-1',
          screenResolution: '1920x1080',
        },
      },
    },
  },
};

function loadServices() {
  try {
    // eslint-disable-next-line import/no-extraneous-dependencies
    Services.chromedriver = require('chromedriver');
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error(err);
  }
}
